### ISSUE TITLE
context sensitivity direction

### ISSUE THREAD

**Issue by dribnet** [kdu4108/context-vs-prior-finetuning#1]
Thanks for publishing your results and for releasing the existing projections as nnpatch models which is very useful for downstream steering applications. In addition, for these projections could you also post the raw vector direction? As an example, the _Refusal in Language Models Is Mediated by a Single Direction_ paper does this by including [a single `direction.pt` file](https://github.com/andyrdt/refusal_direction/tree/main/pipeline/runs/meta-llama-3-8b-instruct) which contains the refusal direction itself for several models. This could be useful for various downstream applications or other types of analysis.

**Comment by jkminder** [comment]
Hi Tom,
the projection matrix `P` is parametrized by the direction vector `u`: `P=uu^T`. That means the nnpatch [LowRankOrthogonalProjection](https://github.com/jkminder/nnpatch/blob/e5b07df13e8481e65010058a6b000bf1ce0d7cc2/nnpatch/subspace/interventions.py#L29) is nothing but a wrapper around the direction. You can get it with

```python
proj = LowRankOrthogonalProjection.from_pretrained("jkminder/CTXPRIOR-Projection-Meta-Llama-3.1-8B-Instruct-L16").to(model.device)
u = proj.weight
u.shape # [4096, 1]
```

Hope this helps. Let me know if I can help in any other way.

**Comment by jkminder** [comment]
Put some pointers in the README. Thanks for raising this issue!

**Comment by dribnet** [comment]
Thanks - can you post your `requirements.txt` and I'll try that.

**Comment by dribnet** [comment]
Thanks Julian - that addition to the README was perfect and I was able to extract the direction and use it downstream successfully. I'll also post those here (as flattened pt files to match the format in the refusal repo) just in case that is helpful for anyone else and close. 👍

[ctxprior-gemma-2-9b-it-L27.pt.zip](https://github.com/user-attachments/files/17784160/ctxprior-gemma-2-9b-it-L27.pt.zip)
[ctxprior-Meta-Llama-3.1-8B-Instruct-L16.pt.zip](https://github.com/user-attachments/files/17784162/ctxprior-Meta-Llama-3.1-8B-Instruct-L16.pt.zip)
[ctxprior-Mistral-7B-Instruct-v0.3-L16.pt.zip](https://github.com/user-attachments/files/17784163/ctxprior-Mistral-7B-Instruct-v0.3-L16.pt.zip)
